# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d35d4f62222a9bd0ca0a8001547de2348da71a2c570d121e2709a55c84a8666641cbb12757d5e482e5c1b4b8a1639d7d25762d517d0449fff2334b18ef4d13b

test:
  secret_key_base: 640e9bc535f04cb5df34f1420305c99e8dabd264d545e1b9f537f0ad0a5d867f8b16235dd07d3dd6c4435dfafbf1ec632b15ea08d3caf27b3327a6dc7ca5b890

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
